repository: free-pdk/free-pdk.github.io
baseurl: ~

title: Free PDK
description: |
  Free PDK is an effort to create an open source alternative to the proprietary
  Padauk µC programmer, as well as adding support to SDCC for Padauk µCs.
github_username: free-pdk
lang: en

permalink: /:title

markdown: kramdown
kramdown:
  input: GFM

theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-titles-from-headings
  - jekyll-mentions
  - jemoji
  - jekyll-timeago

header_pages:
  - tutorial.md

# https://github.com/benbalter/jekyll-titles-from-headings#configuration
titles_from_headings:
  enabled:     true
  strip_title: true

# https://github.com/markets/jekyll-timeago#configuration
jekyll_timeago:
  depth: 2
  threshold: 0.5